##
## Custom Ingress settings. Overrides default Nginx Ingress configuration.
##
customIngress:
  enabled: false
  annotations: {}
  ingressClassName: nginx
  host: moon.moon.svc.cluster.local
  tls: []
  - secretName: ngnix-ingressgateway-certs
    hosts:
    - moon-np.dell.com
  paths:
  - path: /
    port: 8080
  - path: /wd/hub
    port: 4444
  - path: /cypress
    port: 4444
  - path: /playwright
    port: 4444
  - path: /devtools
    port: 4444
  - path: /metrics
    port: 4444
##
## Ingress settings. This chart is using Nginx Ingress. By default, Ingress listens only on port 80 (HTTP).
## Port 443 (HTTPS) is enabled only if TLS certificate and private key are provided in the fields below.
##
ingress:
  ##
  ## Ingress host. Replace this with your domain name.
  ##
  host: moon.moon.svc.cluster.local

  ##
  ## TLS settings. When provided Ingress switches to HTTPS-only mode.
  ##
  tlsCert: 
  tlsKey:

  ##
  ## Ingress proxy timeout settings.
  ##
  proxyConnectTimeout: 1900
  proxySendTimeout: 1900
  proxyReadTimeout: 1900

  ##
  ## Maximum request body size.
  ##
  proxyBodySize: 128m

  type: LoadBalancer
  
  
  ##
  ## Set to true in Openshift.
  ##
  openshift:

##
## Moon deployment settings.
##
deployment:

  ##
  ## Total number of Moon pods. Default is 2.
  ##
  replicas: 5

  ##
  ## Moon pods graceful shutdown timeout. Default is 360 seconds.
  ##
  terminationGracePeriodSeconds:

  ##
  ## Moon container image repository. Default is quay.io/aerokube/moon.
  ##
  moonRepo:

  ##
  ## Moon container image tag. Default equals to chart app version.
  ##
  moonTag:

  ##
  ## Moon container CPU limit. Default is 0.5.
  ##
  moonCPULimit: 1.0

  ##
  ## Moon container CPU request. Default is 0.2.
  ##
  moonCPURequest: 0.25

  ##
  ## Moon container memory limit. Default is 256Mi.
  ## We recommend setting the same value for memory request and limit.
  ##
  moonMemoryLimit: 

  ##
  ## Moon container memory request. Default is 256Mi.
  ##
  moonMemoryRequest: 
  
  ##
  ## Moon-conf image repository. Default is quay.io/aerokube/moon-conf.
  ##
  moonConfRepo:

  ##
  ## Moon-conf container image tag. Default equals to chart app version.
  ##
  moonConfTag:

  ##
  ## Moon-conf container CPU limit. Default is 0.25.
  ##
  moonConfCPULimit:

  ##
  ## Moon-conf container CPU request. Default is 0.05.
  ##
  moonConfCPURequest:

  ##
  ## Moon-conf container memory limit. Default is 128Mi.
  ## We recommend setting the same value for memory request and limit.
  ##
  moonConfMemoryLimit:

  ##
  ## Moon-conf container memory request. Default is 128Mi.
  ##
  moonConfMemoryRequest:

  ##
  ## Moon-ui image repository. Default is quay.io/aerokube/moon-ui.
  ##
  moonUIRepo:

  ##
  ## Moon-ui container image tag. Default equals to chart app version.
  ##
  moonUITag:

  ##
  ## Moon-ui container CPU limit. Default is 0.25.
  ##
  moonUICPULimit:

  ##
  ## Moon-ui container CPU request. Default is 0.05.
  ##
  moonUICPURequest:

  ##
  ## Moon-ui container memory limit. Default is 64Mi.
  ## We recommend setting the same value for memory request and limit.
  ##
  moonUIMemoryLimit:

  ##
  ## Moon-ui container memory request. Default is 64Mi.
  ##
  moonUIMemoryRequest:

  ## If specified, the pod's security policies.
  ## ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  ##
  securityContext: {}
  #  runAsUser: 1000

  ##
  ## Node Selector for Moon pods
  ##
  nodeSelector: {}
  #  kubernetes.io/os: linux

  ## Assign custom affinity rules to the instance
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  affinity: {}
  #  nodeAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      nodeSelectorTerms:
  #      - matchExpressions:
  #        - key: kubernetes.io/e2e-az-name
  #          operator: In
  #          values:
  #          - e2e-az1
  #          - e2e-az2

  #  ## If specified, the pod's priorityClassName.
  #  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
  #  ##
  # priorityClassName: default

  ## If specified, the pod's tolerations.
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  #- key: "key"
  #  operator: "Equal"
  #  value: "value"
  #  effect: "NoSchedul

##
## Available configuration objects.
##
configs:
  ##
  ## Default configuration object. Detailed description of the fields can be found
  ## in documentation: https://aerokube.com/moon/latest/#configuration-object.
  ##
  default:
    serviceAccountName: default
    sessionTimeout: 5m
    user:
      id: 4096
      name: user
    group:
      id: 4096
      name: user
    containers:
      browser:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
      ca-certs:
        repository: quay.io/aerokube/ca-certs
        resources:
          limits:
            cpu: 200m
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 32Mi
      defender:
        repository: quay.io/aerokube/defender
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      video-recorder:
        repository: quay.io/aerokube/video-recorder
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 2Gi
      vnc-server:
        repository: quay.io/aerokube/vnc-server
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      x-server:
        repository: quay.io/aerokube/x-server
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
    storage:
      accessKey: "dur1002112usr"
      bucket: "moon-blobs-np"
      endpoint: "http://cloudstorage.onefs.dell.com"
      filename: ""
      pattern: ""
      secretKey: "pTGENlbPu6ZLnMavmjXQzE7Atvi7bS4QSjpyXiip"

##
## Available browsers set objects.
##
browsers:
  ##
  ## Default browsers set object. Detailed description of the fields can be found
  ## in documentation: https://aerokube.com/moon/latest/#browsers-set.
  ##
  default:
    selenium:
      MicrosoftEdge:
        repository: quay.io/browser/microsoft-edge-stable
        default: 98.0.1108.62-0
      chrome:
        repository: quay.io/browser/google-chrome-stable
        default: 99.0.4844.51-0
      firefox:
        repository: quay.io/browser/firefox-mozilla-build
        default: 98.0.0-0
      safari:
        repository: quay.io/browser/safari
        default: 15.0-0
    cypress:
      electron:
        repository: quay.io/browsers/cypress-electron
      chromium:
        repository: quay.io/browsers/cypress-chromium
      chrome:
        repository: quay.io/browsers/cypress-chrome
      firefox:
        repository: quay.io/browsers/cypress-firefox
      edge:
        repository: quay.io/browsers/cypress-edge
    playwright:
      chrome:
        repository: quay.io/browser/playwright-chrome
      chromium:
        repository: quay.io/browser/playwright-chromium
      firefox:
        repository: quay.io/browser/playwright-firefox
      webkit:
        repository: quay.io/browser/playwright-webkit
    devtools:
      chrome:
        repository: quay.io/browser/devtools-google-chrome-stable

##
## Available quotas. If you need to have multiple quota objects - simply add them below:
##
quota:
  moon: null
  alfa-team:
    namespace: alfa
  beta-team:
    namespace: beta
##
quota:
  ##
  ## Default quota. Detailed description of the fields can be found
  ## in documentation: https://aerokube.com/moon/latest/#quotas. Set it
  ## to null when having multiple quota objects.
  ##
  moon:
    namespace: moon

##
## License key. When empty default free license key is automatically used.
##
license: STZWSHRsR0JsaFVteE1TMDlaYW1NTFlDWUJSTDh3eEdaN2hERmVaalZ5eDhUZFAxT0Rxdzgxd25HRUVXbWFWVHRFRlFaNUNsUnNObFVEeEZ1UnJKMm1rY0Y1N2VWTW1PSzYxSytZUWZsTExhRndvOUtqMU9vWlpZdDNBdVo5VTZ4NDFINmFnWFBmTmZnYUZBNG1SWkRFNEpXZTBLdHhBK200dWtVNkkrS2FjaTQ3eEdhd25zNzNyRzBFczRJcTFRd3hCZHUrUzBnTUc2VTA5NlhzQUhyTE1Hcm56OHJ6UHltMldmUEVWN21VRGNTRVpZZXVMOHRpWFZIMWZUMVB3OWdUbEx0ek9VbWczMGdERnJTSzEwbnZTRjhKTjgvZE5jMmhHakRCM1JrM0l2elRPWUNkNndUL1pBTTRWditBS25URlppSWV2V29kaDlrZklnbjl3WDU4ZFNFL3AyK1NGSUZHMjVwU3JzRjZUdFZwRmN3a3diRE9PVVpCdkh2cFhQbmZVMDAwZ0hEVm41eUc5T1Bjd0VCbFBXQTJ3RmNxQm54alZsUG5JNmFXM2RRdmVYRmlzOTM5cEE4VzhEZTRRVFZ1YXJZeitVczBnRkM0WmVTdlBDdGI1ZjFPSkN4QVY5emFhUjZMVUcvOGhQMTd4aGZnbVliRi80blNTUkVFck1QZjFaMVZLMFB2MkJJK0lLMEZqYk9uMmFVeW05WUNtTkpjeEJMS2oxMjR2U1FTL2RLV3NDSE5HbnZEbzBuSUpkUCt2bEtQd3NQWnRxcG8yTGNCTTJHR3ZwQU9wcE8wdzFuYnp1aWJDTTE0RHlTTGhSeHQzZWlydEFSd0tmZyszdkxqVTArcVdCRG1sRTBFSEFONjBJcXpUS0ZFL0kxQWtvUTI3azRxb3JsQzA9O2V5SnNhV05sYm5ObFpTSTZJa1JsYkd3Z1NXNWpMaUlzSW5CeWIyUjFZM1FpT2lKTmIyOXVJaXdpYldGNFUyVnpjMmx2Ym5NaU9qVXdNQ3dpZEc4aU9qRTJORGczTnpFeU1EQjk=
